* [auto-upgrade-helper][PATCH] devtool: return both stdout and stderr
@ 2022-01-02 16:25 Alexander Kanavin
  0 siblings, 0 replies; only message in thread
From: Alexander Kanavin @ 2022-01-02 16:25 UTC (permalink / raw)
  To: yocto; +Cc: Alexander Kanavin

At some point devtool started printing to stderr, which means
patch rebase issues weren't anymore correctly caught, and bogus
updates were being sent out.

Signed-off-by: Alexander Kanavin <alex.kanavin@gmail.com>
---
 modules/utils/devtool.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/modules/utils/devtool.py b/modules/utils/devtool.py
index 0d27bb0..c26061f 100644
--- a/modules/utils/devtool.py
+++ b/modules/utils/devtool.py
@@ -19,7 +19,7 @@ class Devtool(object):
             raise DevtoolError("The following devtool command failed: " + operation,
                         e.stdout, e.stderr)
 
-        return stdout
+        return stdout + stderr
 
     def upgrade(self, recipe, version = None, revision = None):
         cmd = " upgrade " + recipe
-- 
2.33.1



^ permalink raw reply related	[flat|nested] only message in thread
only message in thread, other threads:[~2022-01-02 16:25 UTC | newest]

Thread overview: (only message) (download: mbox.gz / follow: Atom feed)
-- links below jump to the message on this page --
2022-01-02 16:25 [auto-upgrade-helper][PATCH] devtool: return both stdout and stderr Alexander Kanavin

