* Error while testing "bitbake core-image-base -c testimage -v" #bitbake #dunfell
@ 2023-06-14  8:49 lavkhush2208
  2023-06-15 16:39 ` [yocto] " Khem Raj
  0 siblings, 1 reply; 5+ messages in thread
From: lavkhush2208 @ 2023-06-14  8:49 UTC (permalink / raw)
  To: yocto

[-- Attachment #1: Type: text/plain, Size: 3066 bytes --]

Hi all,

I was testing my *core-image-base -c testimage* with test-suit and getting error:-

*ERROR: core-image-base-1.0-r0 do_testimage: Output from runqemu:*
*runqemu - WARNING - /home/kush/khu/sources/build/tmp-glibc/deploy/images/board/core-image-base-board.qemuboot.conf doesn't exist*
*ls: cannot access '/home/kush/khu/sources/build/tmp-glibc/deploy/images/board/*.qemuboot.conf': No such file or directory*
*runqemu - ERROR - Command 'ls -t /home/kush/khu/sources/build/tmp-glibc/deploy/images/board/*.qemuboot.conf' returned non-zero exit status 2.*
*runqemu - INFO - Cleaning up*

WARNING: core-image-base-1.0-r0 do_testimage: Qemu ended unexpectedly, dump data from host is in /home/integration-team/kush/khu/sources/build/tmp-glibc/log/runtime-hostdump/202306141146_qemu
ERROR: core-image-base-1.0-r0 do_testimage: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
0001:
*** 0002:do_testimage(d)
0003:
File: '/home/integration-team/kush/khu/sources/openembedded-core/meta/classes/testimage.bbclass', lineno: 129, function: do_testimage
0125:    netstat -an
0126:}
0127:
0128:python do_testimage() {
*** 0129:    testimage_main(d)
0130:}
0131:
0132:addtask testimage
0133:do_testimage[nostamp] = "1"
File: '/home/integration-team/kush/khu/sources/openembedded-core/meta/classes/testimage.bbclass', lineno: 371, function: testimage_main
0367:    orig_sigterm_handler = signal.signal(signal.SIGTERM, sigterm_exception)
0368:    try:
0369:        # We need to check if runqemu ends unexpectedly
0370:        # or if the worker send us a SIGTERM
*** 0371:        tc.target.start(params=d.getVar("TEST_QEMUPARAMS"), runqemuparams=d.getVar("TEST_RUNQEMUPARAMS"))
0372:        import threading
0373:        try:
0374:            threading.Timer(int(d.getVar("TEST_OVERALL_TIMEOUT")), handle_test_timeout, (int(d.getVar("TEST_OVERALL_TIMEOUT")),)).start()
0375:        except ValueError:
File: '/home/integration-team/kush/khu/sources/openembedded-core/meta/lib/oeqa/core/target/qemu.py', lineno: 67, function: start
0063:            if self.runner.server_ip:
0064:                self.server_ip = self.runner.server_ip
0065:        else:
0066:            self.stop()
*** 0067:            raise RuntimeError("FAILED to start qemu - check the task log and the boot log")
0068:
0069:    def stop(self):
0070:        self.runner.stop()
Exception: RuntimeError: FAILED to start qemu - check the task log and the boot log

ERROR: Logfile of failure stored in: /home/kush/khu/sources/build/tmp-glibc/work/board-oe-linux/core-image-base/1.0-r0/temp/log.do_testimage.17255
ERROR: Task (/home/kush/khu/sources/meta-exaleap/recipes-images/images/core-image-base.bb:do_testimage) failed with exit code '1'

Can anyone help me in this, where i am doing wrong.

T&R
luvkhush

[-- Attachment #2: Type: text/html, Size: 4628 bytes --]

^ permalink raw reply	[flat|nested] 5+ messages in thread
* Re: [yocto] Error while testing "bitbake core-image-base -c testimage -v" #bitbake #dunfell
  2023-06-14  8:49 Error while testing "bitbake core-image-base -c testimage -v" #bitbake #dunfell lavkhush2208
@ 2023-06-15 16:39 ` Khem Raj
  2023-06-15 16:42   ` sateesh m
  0 siblings, 1 reply; 5+ messages in thread
From: Khem Raj @ 2023-06-15 16:39 UTC (permalink / raw)
  To: lavkhush2208; +Cc: yocto

On Wed, Jun 14, 2023 at 1:49 AM <lavkhush2208@gmail.com> wrote:
>
> Hi all,
>
> I was testing my core-image-base -c testimage with test-suit and getting error:-
>
> ERROR: core-image-base-1.0-r0 do_testimage: Output from runqemu:
> runqemu - WARNING - /home/kush/khu/sources/build/tmp-glibc/deploy/images/board/core-image-base-board.qemuboot.conf doesn't exist

You do not have image built. So first build the image then run tests.

bitbake core-image-base
bitbake core-image-base  -ctestimage

Or you can add TESTIMAGE_AUTO:qemuall = "1" to local.conf  which will run
the tests automatically when doing bitbake core-image-base for any
qemu based machine target and second step is not needed.

> ls: cannot access '/home/kush/khu/sources/build/tmp-glibc/deploy/images/board/*.qemuboot.conf': No such file or directory
> runqemu - ERROR - Command 'ls -t /home/kush/khu/sources/build/tmp-glibc/deploy/images/board/*.qemuboot.conf' returned non-zero exit status 2.
> runqemu - INFO - Cleaning up
>
>
> WARNING: core-image-base-1.0-r0 do_testimage: Qemu ended unexpectedly, dump data from host is in /home/integration-team/kush/khu/sources/build/tmp-glibc/log/runtime-hostdump/202306141146_qemu
> ERROR: core-image-base-1.0-r0 do_testimage: Error executing a python function in exec_python_func() autogenerated:
>
> The stack trace of python calls that resulted in this exception/failure was:
> File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
>      0001:
>  *** 0002:do_testimage(d)
>      0003:
> File: '/home/integration-team/kush/khu/sources/openembedded-core/meta/classes/testimage.bbclass', lineno: 129, function: do_testimage
>      0125:    netstat -an
>      0126:}
>      0127:
>      0128:python do_testimage() {
>  *** 0129:    testimage_main(d)
>      0130:}
>      0131:
>      0132:addtask testimage
>      0133:do_testimage[nostamp] = "1"
> File: '/home/integration-team/kush/khu/sources/openembedded-core/meta/classes/testimage.bbclass', lineno: 371, function: testimage_main
>      0367:    orig_sigterm_handler = signal.signal(signal.SIGTERM, sigterm_exception)
>      0368:    try:
>      0369:        # We need to check if runqemu ends unexpectedly
>      0370:        # or if the worker send us a SIGTERM
>  *** 0371:        tc.target.start(params=d.getVar("TEST_QEMUPARAMS"), runqemuparams=d.getVar("TEST_RUNQEMUPARAMS"))
>      0372:        import threading
>      0373:        try:
>      0374:            threading.Timer(int(d.getVar("TEST_OVERALL_TIMEOUT")), handle_test_timeout, (int(d.getVar("TEST_OVERALL_TIMEOUT")),)).start()
>      0375:        except ValueError:
> File: '/home/integration-team/kush/khu/sources/openembedded-core/meta/lib/oeqa/core/target/qemu.py', lineno: 67, function: start
>      0063:            if self.runner.server_ip:
>      0064:                self.server_ip = self.runner.server_ip
>      0065:        else:
>      0066:            self.stop()
>  *** 0067:            raise RuntimeError("FAILED to start qemu - check the task log and the boot log")
>      0068:
>      0069:    def stop(self):
>      0070:        self.runner.stop()
> Exception: RuntimeError: FAILED to start qemu - check the task log and the boot log
>
> ERROR: Logfile of failure stored in: /home/kush/khu/sources/build/tmp-glibc/work/board-oe-linux/core-image-base/1.0-r0/temp/log.do_testimage.17255
> ERROR: Task (/home/kush/khu/sources/meta-exaleap/recipes-images/images/core-image-base.bb:do_testimage) failed with exit code '1'
>
> Can anyone help me in this, where i am doing wrong.
>
> T&R
> luvkhush
>
> -=-=-=-=-=-=-=-=-=-=-=-
> Links: You receive all messages sent to this group.
> You automatically follow any topics you start or reply to.
> View/Reply Online (#60287): https://lists.yoctoproject.org/g/yocto/message/60287
> Mute This Topic: https://lists.yoctoproject.org/mt/99523749/1997914
> Mute #bitbake:https://lists.yoctoproject.org/g/yocto/mutehashtag/bitbake
> Mute #dunfell:https://lists.yoctoproject.org/g/yocto/mutehashtag/dunfell
> Group Owner: yocto+owner@lists.yoctoproject.org
> Unsubscribe: https://lists.yoctoproject.org/g/yocto/unsub [raj.khem@gmail.com]
> -=-=-=-=-=-=-=-=-=-=-=-
>


^ permalink raw reply	[flat|nested] 5+ messages in thread
* Re: [yocto] Error while testing "bitbake core-image-base -c testimage -v" #bitbake #dunfell
  2023-06-15 16:39 ` [yocto] " Khem Raj
@ 2023-06-15 16:42   ` sateesh m
  2023-06-15 17:07     ` Khem Raj
  0 siblings, 1 reply; 5+ messages in thread
From: sateesh m @ 2023-06-15 16:42 UTC (permalink / raw)
  To: Khem Raj; +Cc: lavkhush2208, yocto

[-- Attachment #1: Type: text/plain, Size: 4711 bytes --]

We don't want to build qemu at all. We are building  for our custom target
machine.

Same commands we have executed we want to exclude qemu test running. Only
our target  testimage should pass .


Regards,
Sateesh

On Thu, 15 Jun, 2023, 10:10 pm Khem Raj, <raj.khem@gmail.com> wrote:

> On Wed, Jun 14, 2023 at 1:49 AM <lavkhush2208@gmail.com> wrote:
> >
> > Hi all,
> >
> > I was testing my core-image-base -c testimage with test-suit and getting
> error:-
> >
> > ERROR: core-image-base-1.0-r0 do_testimage: Output from runqemu:
> > runqemu - WARNING -
> /home/kush/khu/sources/build/tmp-glibc/deploy/images/board/core-image-base-board.qemuboot.conf
> doesn't exist
>
> You do not have image built. So first build the image then run tests.
>
> bitbake core-image-base
> bitbake core-image-base  -ctestimage
>
> Or you can add TESTIMAGE_AUTO:qemuall = "1" to local.conf  which will run
> the tests automatically when doing bitbake core-image-base for any
> qemu based machine target and second step is not needed.
>
> > ls: cannot access
> '/home/kush/khu/sources/build/tmp-glibc/deploy/images/board/*.qemuboot.conf':
> No such file or directory
> > runqemu - ERROR - Command 'ls -t
> /home/kush/khu/sources/build/tmp-glibc/deploy/images/board/*.qemuboot.conf'
> returned non-zero exit status 2.
> > runqemu - INFO - Cleaning up
> >
> >
> > WARNING: core-image-base-1.0-r0 do_testimage: Qemu ended unexpectedly,
> dump data from host is in
> /home/integration-team/kush/khu/sources/build/tmp-glibc/log/runtime-hostdump/202306141146_qemu
> > ERROR: core-image-base-1.0-r0 do_testimage: Error executing a python
> function in exec_python_func() autogenerated:
> >
> > The stack trace of python calls that resulted in this exception/failure
> was:
> > File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
> >      0001:
> >  *** 0002:do_testimage(d)
> >      0003:
> > File:
> '/home/integration-team/kush/khu/sources/openembedded-core/meta/classes/testimage.bbclass',
> lineno: 129, function: do_testimage
> >      0125:    netstat -an
> >      0126:}
> >      0127:
> >      0128:python do_testimage() {
> >  *** 0129:    testimage_main(d)
> >      0130:}
> >      0131:
> >      0132:addtask testimage
> >      0133:do_testimage[nostamp] = "1"
> > File:
> '/home/integration-team/kush/khu/sources/openembedded-core/meta/classes/testimage.bbclass',
> lineno: 371, function: testimage_main
> >      0367:    orig_sigterm_handler = signal.signal(signal.SIGTERM,
> sigterm_exception)
> >      0368:    try:
> >      0369:        # We need to check if runqemu ends unexpectedly
> >      0370:        # or if the worker send us a SIGTERM
> >  *** 0371:        tc.target.start(params=d.getVar("TEST_QEMUPARAMS"),
> runqemuparams=d.getVar("TEST_RUNQEMUPARAMS"))
> >      0372:        import threading
> >      0373:        try:
> >      0374:
> threading.Timer(int(d.getVar("TEST_OVERALL_TIMEOUT")), handle_test_timeout,
> (int(d.getVar("TEST_OVERALL_TIMEOUT")),)).start()
> >      0375:        except ValueError:
> > File:
> '/home/integration-team/kush/khu/sources/openembedded-core/meta/lib/oeqa/core/target/qemu.py',
> lineno: 67, function: start
> >      0063:            if self.runner.server_ip:
> >      0064:                self.server_ip = self.runner.server_ip
> >      0065:        else:
> >      0066:            self.stop()
> >  *** 0067:            raise RuntimeError("FAILED to start qemu - check
> the task log and the boot log")
> >      0068:
> >      0069:    def stop(self):
> >      0070:        self.runner.stop()
> > Exception: RuntimeError: FAILED to start qemu - check the task log and
> the boot log
> >
> > ERROR: Logfile of failure stored in:
> /home/kush/khu/sources/build/tmp-glibc/work/board-oe-linux/core-image-base/1.0-r0/temp/log.do_testimage.17255
> > ERROR: Task
> (/home/kush/khu/sources/meta-exaleap/recipes-images/images/core-image-base.bb:do_testimage)
> failed with exit code '1'
> >
> > Can anyone help me in this, where i am doing wrong.
> >
> > T&R
> > luvkhush
> >
> >
> >
>
> -=-=-=-=-=-=-=-=-=-=-=-
> Links: You receive all messages sent to this group.
> View/Reply Online (#60318):
> https://lists.yoctoproject.org/g/yocto/message/60318
> Mute This Topic: https://lists.yoctoproject.org/mt/99523749/4526955
> Mute #bitbake:https://lists.yoctoproject.org/g/yocto/mutehashtag/bitbake
> Mute #dunfell:https://lists.yoctoproject.org/g/yocto/mutehashtag/dunfell
> Group Owner: yocto+owner@lists.yoctoproject.org
> Unsubscribe: https://lists.yoctoproject.org/g/yocto/unsub [
> sateesh0457@gmail.com]
> -=-=-=-=-=-=-=-=-=-=-=-
>
>

[-- Attachment #2: Type: text/html, Size: 6486 bytes --]

^ permalink raw reply	[flat|nested] 5+ messages in thread
* Re: [yocto] Error while testing "bitbake core-image-base -c testimage -v" #bitbake #dunfell
  2023-06-15 16:42   ` sateesh m
@ 2023-06-15 17:07     ` Khem Raj
  2023-06-16 11:21       ` sateesh m
  0 siblings, 1 reply; 5+ messages in thread
From: Khem Raj @ 2023-06-15 17:07 UTC (permalink / raw)
  To: sateesh m; +Cc: lavkhush2208, yocto

for real targets. You need to do some steps

add following to conf/local.conf

TEST_SERVER_IP = "<ip of build machine>"
MAGE_FEATURES:append = " debug-tweaks"
DISTRO_FEATURES:append = " ptest"
TEST_TARGET_IP = "<ip of target board>"
TEST_TARGET = "simpleremote"

2. Build image
3. flash this image on to target ( different boards may need different
instructions )
4. boot the target and ensure its connected to network and has IP address
5. run bitbake -ctestimage <image>

On Thu, Jun 15, 2023 at 9:42 AM sateesh m <sateesh0457@gmail.com> wrote:
>
> We don't want to build qemu at all. We are building  for our custom target machine.
>
> Same commands we have executed we want to exclude qemu test running. Only our target  testimage should pass .
>
>
> Regards,
> Sateesh
>
> On Thu, 15 Jun, 2023, 10:10 pm Khem Raj, <raj.khem@gmail.com> wrote:
>>
>> On Wed, Jun 14, 2023 at 1:49 AM <lavkhush2208@gmail.com> wrote:
>> >
>> > Hi all,
>> >
>> > I was testing my core-image-base -c testimage with test-suit and getting error:-
>> >
>> > ERROR: core-image-base-1.0-r0 do_testimage: Output from runqemu:
>> > runqemu - WARNING - /home/kush/khu/sources/build/tmp-glibc/deploy/images/board/core-image-base-board.qemuboot.conf doesn't exist
>>
>> You do not have image built. So first build the image then run tests.
>>
>> bitbake core-image-base
>> bitbake core-image-base  -ctestimage
>>
>> Or you can add TESTIMAGE_AUTO:qemuall = "1" to local.conf  which will run
>> the tests automatically when doing bitbake core-image-base for any
>> qemu based machine target and second step is not needed.
>>
>> > ls: cannot access '/home/kush/khu/sources/build/tmp-glibc/deploy/images/board/*.qemuboot.conf': No such file or directory
>> > runqemu - ERROR - Command 'ls -t /home/kush/khu/sources/build/tmp-glibc/deploy/images/board/*.qemuboot.conf' returned non-zero exit status 2.
>> > runqemu - INFO - Cleaning up
>> >
>> >
>> > WARNING: core-image-base-1.0-r0 do_testimage: Qemu ended unexpectedly, dump data from host is in /home/integration-team/kush/khu/sources/build/tmp-glibc/log/runtime-hostdump/202306141146_qemu
>> > ERROR: core-image-base-1.0-r0 do_testimage: Error executing a python function in exec_python_func() autogenerated:
>> >
>> > The stack trace of python calls that resulted in this exception/failure was:
>> > File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
>> >      0001:
>> >  *** 0002:do_testimage(d)
>> >      0003:
>> > File: '/home/integration-team/kush/khu/sources/openembedded-core/meta/classes/testimage.bbclass', lineno: 129, function: do_testimage
>> >      0125:    netstat -an
>> >      0126:}
>> >      0127:
>> >      0128:python do_testimage() {
>> >  *** 0129:    testimage_main(d)
>> >      0130:}
>> >      0131:
>> >      0132:addtask testimage
>> >      0133:do_testimage[nostamp] = "1"
>> > File: '/home/integration-team/kush/khu/sources/openembedded-core/meta/classes/testimage.bbclass', lineno: 371, function: testimage_main
>> >      0367:    orig_sigterm_handler = signal.signal(signal.SIGTERM, sigterm_exception)
>> >      0368:    try:
>> >      0369:        # We need to check if runqemu ends unexpectedly
>> >      0370:        # or if the worker send us a SIGTERM
>> >  *** 0371:        tc.target.start(params=d.getVar("TEST_QEMUPARAMS"), runqemuparams=d.getVar("TEST_RUNQEMUPARAMS"))
>> >      0372:        import threading
>> >      0373:        try:
>> >      0374:            threading.Timer(int(d.getVar("TEST_OVERALL_TIMEOUT")), handle_test_timeout, (int(d.getVar("TEST_OVERALL_TIMEOUT")),)).start()
>> >      0375:        except ValueError:
>> > File: '/home/integration-team/kush/khu/sources/openembedded-core/meta/lib/oeqa/core/target/qemu.py', lineno: 67, function: start
>> >      0063:            if self.runner.server_ip:
>> >      0064:                self.server_ip = self.runner.server_ip
>> >      0065:        else:
>> >      0066:            self.stop()
>> >  *** 0067:            raise RuntimeError("FAILED to start qemu - check the task log and the boot log")
>> >      0068:
>> >      0069:    def stop(self):
>> >      0070:        self.runner.stop()
>> > Exception: RuntimeError: FAILED to start qemu - check the task log and the boot log
>> >
>> > ERROR: Logfile of failure stored in: /home/kush/khu/sources/build/tmp-glibc/work/board-oe-linux/core-image-base/1.0-r0/temp/log.do_testimage.17255
>> > ERROR: Task (/home/kush/khu/sources/meta-exaleap/recipes-images/images/core-image-base.bb:do_testimage) failed with exit code '1'
>> >
>> > Can anyone help me in this, where i am doing wrong.
>> >
>> > T&R
>> > luvkhush
>> >
>> >
>> >
>>
>> -=-=-=-=-=-=-=-=-=-=-=-
>> Links: You receive all messages sent to this group.
>> View/Reply Online (#60318): https://lists.yoctoproject.org/g/yocto/message/60318
>> Mute This Topic: https://lists.yoctoproject.org/mt/99523749/4526955
>> Mute #bitbake:https://lists.yoctoproject.org/g/yocto/mutehashtag/bitbake
>> Mute #dunfell:https://lists.yoctoproject.org/g/yocto/mutehashtag/dunfell
>> Group Owner: yocto+owner@lists.yoctoproject.org
>> Unsubscribe: https://lists.yoctoproject.org/g/yocto/unsub [sateesh0457@gmail.com]
>> -=-=-=-=-=-=-=-=-=-=-=-
>>


^ permalink raw reply	[flat|nested] 5+ messages in thread
* Re: [yocto] Error while testing "bitbake core-image-base -c testimage -v" #bitbake #dunfell
  2023-06-15 17:07     ` Khem Raj
@ 2023-06-16 11:21       ` sateesh m
  0 siblings, 0 replies; 5+ messages in thread
From: sateesh m @ 2023-06-16 11:21 UTC (permalink / raw)
  To: Khem Raj; +Cc: lavkhush2208, yocto

[-- Attachment #1: Type: text/plain, Size: 5765 bytes --]

Very helpful! Issue fixed.

Thank you Khem Raj.


Regards,
Sateesh


On Thu, 15 Jun, 2023, 10:37 pm Khem Raj, <raj.khem@gmail.com> wrote:

> for real targets. You need to do some steps
>
> add following to conf/local.conf
>
> TEST_SERVER_IP = "<ip of build machine>"
> MAGE_FEATURES:append = " debug-tweaks"
> DISTRO_FEATURES:append = " ptest"
> TEST_TARGET_IP = "<ip of target board>"
> TEST_TARGET = "simpleremote"
>
> 2. Build image
> 3. flash this image on to target ( different boards may need different
> instructions )
> 4. boot the target and ensure its connected to network and has IP address
> 5. run bitbake -ctestimage <image>
>
> On Thu, Jun 15, 2023 at 9:42 AM sateesh m <sateesh0457@gmail.com> wrote:
> >
> > We don't want to build qemu at all. We are building  for our custom
> target machine.
> >
> > Same commands we have executed we want to exclude qemu test running.
> Only our target  testimage should pass .
> >
> >
> > Regards,
> > Sateesh
> >
> > On Thu, 15 Jun, 2023, 10:10 pm Khem Raj, <raj.khem@gmail.com> wrote:
> >>
> >> On Wed, Jun 14, 2023 at 1:49 AM <lavkhush2208@gmail.com> wrote:
> >> >
> >> > Hi all,
> >> >
> >> > I was testing my core-image-base -c testimage with test-suit and
> getting error:-
> >> >
> >> > ERROR: core-image-base-1.0-r0 do_testimage: Output from runqemu:
> >> > runqemu - WARNING -
> /home/kush/khu/sources/build/tmp-glibc/deploy/images/board/core-image-base-board.qemuboot.conf
> doesn't exist
> >>
> >> You do not have image built. So first build the image then run tests.
> >>
> >> bitbake core-image-base
> >> bitbake core-image-base  -ctestimage
> >>
> >> Or you can add TESTIMAGE_AUTO:qemuall = "1" to local.conf  which will
> run
> >> the tests automatically when doing bitbake core-image-base for any
> >> qemu based machine target and second step is not needed.
> >>
> >> > ls: cannot access
> '/home/kush/khu/sources/build/tmp-glibc/deploy/images/board/*.qemuboot.conf':
> No such file or directory
> >> > runqemu - ERROR - Command 'ls -t
> /home/kush/khu/sources/build/tmp-glibc/deploy/images/board/*.qemuboot.conf'
> returned non-zero exit status 2.
> >> > runqemu - INFO - Cleaning up
> >> >
> >> >
> >> > WARNING: core-image-base-1.0-r0 do_testimage: Qemu ended
> unexpectedly, dump data from host is in
> /home/integration-team/kush/khu/sources/build/tmp-glibc/log/runtime-hostdump/202306141146_qemu
> >> > ERROR: core-image-base-1.0-r0 do_testimage: Error executing a python
> function in exec_python_func() autogenerated:
> >> >
> >> > The stack trace of python calls that resulted in this
> exception/failure was:
> >> > File: 'exec_python_func() autogenerated', lineno: 2, function:
> <module>
> >> >      0001:
> >> >  *** 0002:do_testimage(d)
> >> >      0003:
> >> > File:
> '/home/integration-team/kush/khu/sources/openembedded-core/meta/classes/testimage.bbclass',
> lineno: 129, function: do_testimage
> >> >      0125:    netstat -an
> >> >      0126:}
> >> >      0127:
> >> >      0128:python do_testimage() {
> >> >  *** 0129:    testimage_main(d)
> >> >      0130:}
> >> >      0131:
> >> >      0132:addtask testimage
> >> >      0133:do_testimage[nostamp] = "1"
> >> > File:
> '/home/integration-team/kush/khu/sources/openembedded-core/meta/classes/testimage.bbclass',
> lineno: 371, function: testimage_main
> >> >      0367:    orig_sigterm_handler = signal.signal(signal.SIGTERM,
> sigterm_exception)
> >> >      0368:    try:
> >> >      0369:        # We need to check if runqemu ends unexpectedly
> >> >      0370:        # or if the worker send us a SIGTERM
> >> >  *** 0371:        tc.target.start(params=d.getVar("TEST_QEMUPARAMS"),
> runqemuparams=d.getVar("TEST_RUNQEMUPARAMS"))
> >> >      0372:        import threading
> >> >      0373:        try:
> >> >      0374:
> threading.Timer(int(d.getVar("TEST_OVERALL_TIMEOUT")), handle_test_timeout,
> (int(d.getVar("TEST_OVERALL_TIMEOUT")),)).start()
> >> >      0375:        except ValueError:
> >> > File:
> '/home/integration-team/kush/khu/sources/openembedded-core/meta/lib/oeqa/core/target/qemu.py',
> lineno: 67, function: start
> >> >      0063:            if self.runner.server_ip:
> >> >      0064:                self.server_ip = self.runner.server_ip
> >> >      0065:        else:
> >> >      0066:            self.stop()
> >> >  *** 0067:            raise RuntimeError("FAILED to start qemu -
> check the task log and the boot log")
> >> >      0068:
> >> >      0069:    def stop(self):
> >> >      0070:        self.runner.stop()
> >> > Exception: RuntimeError: FAILED to start qemu - check the task log
> and the boot log
> >> >
> >> > ERROR: Logfile of failure stored in:
> /home/kush/khu/sources/build/tmp-glibc/work/board-oe-linux/core-image-base/1.0-r0/temp/log.do_testimage.17255
> >> > ERROR: Task
> (/home/kush/khu/sources/meta-exaleap/recipes-images/images/core-image-base.bb:do_testimage)
> failed with exit code '1'
> >> >
> >> > Can anyone help me in this, where i am doing wrong.
> >> >
> >> > T&R
> >> > luvkhush
> >> >
> >> >
> >> >
> >>
> >> -=-=-=-=-=-=-=-=-=-=-=-
> >> Links: You receive all messages sent to this group.
> >> View/Reply Online (#60318):
> https://lists.yoctoproject.org/g/yocto/message/60318
> >> Mute This Topic: https://lists.yoctoproject.org/mt/99523749/4526955
> >> Mute #bitbake:
> https://lists.yoctoproject.org/g/yocto/mutehashtag/bitbake
> >> Mute #dunfell:
> https://lists.yoctoproject.org/g/yocto/mutehashtag/dunfell
> >> Group Owner: yocto+owner@lists.yoctoproject.org
> >> Unsubscribe: https://lists.yoctoproject.org/g/yocto/unsub [
> sateesh0457@gmail.com]
> >> -=-=-=-=-=-=-=-=-=-=-=-
> >>
>

[-- Attachment #2: Type: text/html, Size: 8360 bytes --]

^ permalink raw reply	[flat|nested] 5+ messages in thread
end of thread, other threads:[~2023-06-16 11:21 UTC | newest]

Thread overview: 5+ messages (download: mbox.gz / follow: Atom feed)
-- links below jump to the message on this page --
2023-06-14  8:49 Error while testing "bitbake core-image-base -c testimage -v" #bitbake #dunfell lavkhush2208
2023-06-15 16:39 ` [yocto] " Khem Raj
2023-06-15 16:42   ` sateesh m
2023-06-15 17:07     ` Khem Raj
2023-06-16 11:21       ` sateesh m

